

before_script:
  - make data
  - make germline

stages:
  - test_unit
  - deploy

test_browser_unit:
  stage: test_unit
  script: make unit_browser
  artifacts:
    paths:
    - browser/

deploy:
  stage: deploy
  script:
    - rsync -av --delete browser vidjil-ci@vda.vidjil.org:ci/environments/review/$CI_BUILD_REF_SLUG
    - scp doc/analysis-example.vidjil vidjil-ci@vda.vidjil.org:ci/environments/review/$CI_BUILD_REF_SLUG/browser/
  environment:
    name: $CI_BUILD_REF_NAME
    url: https://$CI_BUILD_REF_SLUG.ci.vidjil.org/browser/?data=analysis-example.vidjil
