language: cpp
compiler: gcc

before_install:
  - sudo pip install cpp-coveralls
  - sudo apt-get update
  - sudo apt-get install org-mode

before_script: make data ; make germline

script: 
  - make COVERAGE=1 && make COVERAGE=1 test
  - make unit_browser

after_success:
  - make should_coveralls
