language: cpp
compiler: gcc

before_install:
  - sudo pip install cpp-coveralls

before_script: make data ; make germline

script:
  ###
  - echo '"Build..."' && echo -en 'travis_fold:start:script.build\\r'
  - make COVERAGE=1
  - echo -en 'travis_fold:end:script.build\\r'
  ###
  - echo '"Tests, Algo (unit)..."'  && echo -en 'travis_fold:start:script.test-algo-unit\\r'
  - make COVERAGE=1 unit
  - echo -en 'travis_fold:end:script.test-algo-unit\\r'
  ###
  - echo '"Tests, Algo (functional, .should_get)..."'  && echo -en 'travis_fold:start:script.test-algo-functional\\r'
  - make COVERAGE=1 should
  - echo -en 'travis_fold:end:script.test-algo-functional\\r'
  ###
  - echo '"Tests, Algo (functional, .should-vdj.fa)..."'  && echo -en 'travis_fold:start:script.test-algo-functional-vdj\\r'
  - make COVERAGE=1 shouldvdj
  - echo -en 'travis_fold:end:script.test-algo-functional-vdj\\r'
  ###
  - echo '"Tests, Tools..."'  && echo -en 'travis_fold:start:script.test-tools\\r'
  - make test_tools
  - echo -en 'travis_fold:end:script.test-tools\\r'
  ###
  - echo '"Tests, Browser (unit)..."'  && echo -en 'travis_fold:start:script.test-browser-unit\\r'
  - make unit_browser
  - echo -en 'travis_fold:end:script.test-browser-unit\\r'

after_success:
  - make should_coveralls

notifications:
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis
