language: cpp
compiler: gcc

before_install:
  - sudo pip install cpp-coveralls

before_script: make data ; make germline

script: 
  - make COVERAGE=1 && make COVERAGE=1 test
  - make unit_browser

after_success:
  - make should_coveralls

notifications:
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis
