sudo: false

language: cpp
compiler: gcc

cache:
  apt: true
  pip: true

addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8
   env: COMPILER=g++-4.8

before_install:
  - export PATH="$HOME/.local/bin:$PATH"
  - pip install --user cpp-coveralls

before_script: make data ; make germline

script:
  - export CXX="g++-4.8"
  - g++ --version
  - $CXX --version
  ###
  - echo '"Build..."' && echo -en 'travis_fold:start:script.build\\r'
  - make
  - echo -en 'travis_fold:end:script.build\\r'
  ###
  - echo '"Tests, Algo (unit)..."'  && echo -en 'travis_fold:start:script.test-algo-unit\\r'
  - make unit
  - echo -en 'travis_fold:end:script.test-algo-unit\\r'
  ###
  - echo '"Tests, Algo (functional, .should_get)..."'  && echo -en 'travis_fold:start:script.test-algo-functional\\r'
  - make COVERAGE=1 should
  - echo -en 'travis_fold:end:script.test-algo-functional\\r'
  - make clean
  ###
  - echo '"Tests, Algo (functional, .should-vdj.fa)..."'  && echo -en 'travis_fold:start:script.test-algo-functional-vdj\\r'
  - make shouldvdj
  - echo -en 'travis_fold:end:script.test-algo-functional-vdj\\r'
  ###
  - echo '"Tests, Tools..."'  && echo -en 'travis_fold:start:script.test-tools\\r'
  - make test_tools
  - echo -en 'travis_fold:end:script.test-tools\\r'
  ###
  - echo '"Tests, Browser (unit)..."'  && echo -en 'travis_fold:start:script.test-browser-unit\\r'
  - make unit_browser
  - echo -en 'travis_fold:end:script.test-browser-unit\\r'

after_success:
  - make should_coveralls COVERALLS_OPTIONS="--gcov /usr/bin/gcov-4.8"

notifications:
  email:
    - notifications@vidjil.org
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis
