site_name: Vidjil

docs_dir: doc

plugins: []

repo_url: https://gitlab.inria.fr/vidjil/vidjil
repo_name: gitlab

pages:
    - / : index.md
    - web platform, user manual: user.md
    - locus and recombinations: locus.md
    - vidjil-algo: vidjil-algo.md
    - .vidjil file format: vidjil-format.md
    - server installation/maintenance: server.md
    - credits: credits.md

extra_css:
    - mkdocs-extra.css

